### ISSUE TITLE
Infinite photo loading

### ISSUE THREAD

**Issue by sashabely221100** [Tehzombie-secret/Marketplace-previewer#1]
В секции с отзывами, если отзыв под товаром только 1, раскрыть картинку на фуллскрин и нажать на стрелку для отображения нэкст фотки, крутится бесконечный лоудер

[link](https://www.mkpl-fdbck-view.ru/wb/product/5643094)

**Comment by Tehzombie-secret** [comment]
могу воспроизвести, поправлю. Спасибо!

**Comment by Tehzombie-secret** [comment]
via 83412c7
