### ISSUE TITLE
Не открываются профили 

### ISSUE THREAD

**Issue by skate888** [Tehzombie-secret/Marketplace-previewer#16]
Привет! Перестали открываться профили, когда переходишь по ссылке в профиль появляется только надпись "без имени" и все, и когда находишься в просмотре галереи фотоотзывов надпись "этот отзыв скрыт". Приложу скрины, чтобы было понятней в чем проблема и так с любыми профилями и отзывами. Фиксится как-нибудь это? Заранее огромное спасибо, если да!
![2023-05-04_02-09-52](https://user-images.githubusercontent.com/130507097/236070794-bf178d41-1ab2-4209-8553-7eeb70042c7e.png)
![2023-05-04_02-10-05](https://user-images.githubusercontent.com/130507097/236070841-581a126f-897d-4bd4-8f7d-d882f893ddd6.png)

**Comment by Tehzombie-secret** [comment]
платформа закрыла профили для просмотра - на самом сайте это тоже можно увидеть что перехода в них больше нет. Это фиксится, но займет некоторое время - придется потерпеть несколько недель

**Comment by skate888** [comment]
Доброго времени суток! Так понимаю, никакой надежды что сайт снова заработает нет?) Или еще есть шансы?

**Comment by Tehzombie-secret** [comment]
решение на бумаге есть, просто нынче занят и не знаю сколько реализация займет - может месяц, может и меньше. Я дам знать в этот ишью если будет какое-то продвижение

**Comment by kain199309** [comment]
Видимо Всё, это конец :(

**Comment by Tehzombie-secret** [comment]
я помню про это, но пока реально нет времени этим заниматься

**Comment by Tehzombie-secret** [comment]
апдейт: на пк скрапить огромный маркетплейс оказалось сложнее чем думал: их сервер начинает замедлять и отбрасывать мои запросы, по скромным подсчетам только получить все товары заняло бы месяц, не говоря про сами фидбеки по каждому товару

Выход вижу в следующем - перенести все мощности в клауды, но для эффективного их использования надо продумывать архитектуру, в данный момент сейчас на это уходят все основные силы (когда есть время на это)

**Comment by Tehzombie-secret** [comment]
апдейт: в ближайшие пару дней все будет готово. Половина профилей доступны уже сейчас

**Comment by skate888** [comment]
> апдейт: в ближайшие пару дней все будет готово. Половина профилей доступны уже сейчас

Круто, спасибо что не забросил эту тему 🤝🤝🤝

**Comment by Tehzombie-secret** [comment]
на данный момент можно заявить что проблема полностью решена

**Comment by packsss** [comment]
@Tehzombie-secret подскажи, ты в итоге сейчас собрал страницы пользователей в локальную БД (через парсинг всех отзывов) или нашел wbAPI как получить страницу пользователя?

**Comment by VagrantAI-c** [comment]
> @Tehzombie-secret подскажи, ты в итоге сейчас собрал страницы пользователей в локальную БД (через парсинг всех отзывов) или нашел wbAPI как получить страницу пользователя?

через парсинг. Все не все, но первые 50 страниц каждой категории. Точно что-то осталось за бортом, как это дополнять - пока не уверен

**Comment by Tehzombie-secret** [comment]
> @Tehzombie-secret подскажи, ты в итоге сейчас собрал страницы пользователей в локальную БД (через парсинг всех отзывов) или нашел wbAPI как получить страницу пользователя?

через парсинг. Все не все, но первые 50 страниц каждой категории. Точно что-то осталось за бортом, как это дополнять - пока не уверен
