### ISSUE TITLE
Перестали грузиться отзывы

### ISSUE THREAD

**Issue by ybivec** [Tehzombie-secret/Marketplace-previewer#19]
Перестали грузиться отзывы, заходя на товар появляется загрузка, а после этого пустая страница
![Скрин с проблемой](https://github.com/Tehzombie-secret/Marketplace-previewer/assets/139929042/bd33f95e-dead-4ab1-9ed0-81bd9d154554)
![Консоль](https://github.com/Tehzombie-secret/Marketplace-previewer/assets/139929042/6eaf0fe1-5afe-46d8-bf28-912a4716947c)

**Comment by Tehzombie-secret** [comment]
Спасибо, посмотрю сегодня

**Comment by Tehzombie-secret** [comment]
done
