### ISSUE TITLE
Сайт фактически не функционирует

### ISSUE THREAD

**Issue by Bredberley** [Tehzombie-secret/Marketplace-previewer#21]
Добрый день, сайт фактически не работает, данная проблема у всех или нет?
Профиля тех, кто оставил отзыв не открываются, хотя Вы вроде как пофиксили этот момент.
"Каталог" товаров не появляется на главной при выборе "площадки". Когда ни когда срабатывает поиск по поисковой строке, но также через раз и т.п.
Ни через украинский (основной IP) ни через VPN'овые разные страны работать нормально отказывается.
Что-то с сайтом? Или это на моей стороне что-то? 

Скриншот консольных ошибок прикрепляю 
![Uploading Скрин ВБ отзывы.png…]()

**Comment by kain199309** [comment]
Брат, так это давно уже. Вб закрыли доступ к просмотру профилей и меняют ссылки на товары. Уже есть топик, вот ссылка https://github.com/Tehzombie-secret/Marketplace-previewer/issues/16  . Босс уже все делает, жди новостей.
