### ISSUE TITLE
Не работают фотографии в отзывах 

### ISSUE THREAD

**Issue by petwimdin** [Tehzombie-secret/Marketplace-previewer#25]
![Снимо1к](https://github.com/Tehzombie-secret/Marketplace-previewer/assets/153343692/b372a143-f63f-4cf7-b7f4-b395461f7f55)
![Снимок](https://github.com/Tehzombie-secret/Marketplace-previewer/assets/153343692/299816eb-387c-4014-aba0-e94b61ea25ba)
Сами отзывы видно в профиле, но фотографий нет совсем, так же при входе в карточку товаров нет ничего

**Comment by Tehzombie-secret** [comment]
загрузил рандомный отзыв и товар - все на месте. Есть пример неработающей страницы?

**Comment by vivon828** [comment]
Вообще сайт не работает !  Походу все ((((

**Comment by Tehzombie-secret** [comment]
Сайт поднял

**Comment by Tehzombie-secret** [comment]
поправил
