### ISSUE TITLE
Не отображаются фото в профилях

### ISSUE THREAD

**Issue by Kr11k** [Tehzombie-secret/Marketplace-previewer#27]
![IMG_20231211_150716](https://github.com/Tehzombie-secret/Marketplace-previewer/assets/153486472/86622461-c775-452f-804a-d8ae85bbf491)

**Comment by Tehzombie-secret** [comment]
нужна ссылка

**Comment by Kr11k** [comment]
https://www.mkpl-fdbck-view.ru/wb/person/50157018 например вот, но я сколько профилей хотел посмотреть, они все не отображались

**Comment by Tehzombie-secret** [comment]
да, наблюдаю проблему с базой, сейчас гляну, спасибо

**Comment by Tehzombie-secret** [comment]
поправил
