### ISSUE TITLE
Предложение

### ISSUE THREAD

**Issue by K1ropata** [Tehzombie-secret/Marketplace-previewer#29]
Здравствуйте! У меня есть взаимовыгодное предложение, свяжитесь со мной в телеграм @srpscorpe для уточнения, пожалуйста!

**Comment by Nextan** [comment]
- Сайт показывает лишь те отзывы, с которыми были прикреплены фотографии, возможно ли перейти в профиль по отзыву, но который без фотографии(это по сути и предложение и вопрос) =)
- Либо как получить ссылку на профиль, дабы потом в дальнешем ввести его на самом сайте и соответственно перейти в профиль.
