### ISSUE TITLE
Scroll lock in mobile version

### ISSUE THREAD

**Issue by RomaRo228** [Tehzombie-secret/Marketplace-previewer#3]
![Screenshot_20221021-113548_Chrome](https://user-images.githubusercontent.com/116348956/197165123-fd698933-9551-46a6-a86c-eabb03804428.jpg)
Если раньше можно было проскроллить до нижней секции, где виден отзыв, дата, пользователь и его другие отзывы, то сейчас основной скролл заканчивается раньше, а для нижней секции отдельное маленькое окно и скролл

**Comment by Tehzombie-secret** [comment]
via a1ec669a71cabdd1d7d05e425e6448f7a1689316
