### ISSUE TITLE
Текстовые отзывы(без фото)

### ISSUE THREAD

**Issue by Nextan** [Tehzombie-secret/Marketplace-previewer#30]
- Сайт показывает лишь те отзывы, с которыми были прикреплены фотографии, возможно ли перейти в профиль по отзыву, но который без фотографии (это по сути и предложение и вопрос);
- Либо как получить ссылку на профиль WB, дабы потом в дальнешем ввести его на самом сайте(Вашем) и соответственно перейти в профиль.

**Comment by Nextan** [comment]
Да вот в том-то и беда, что отзывы пользователей, а точнее их "аватарка, ник и.т.п" - не кликабельны, в отличия от того же Ozon'a.
И соответственно, получить ссылку на данный профиль - не получается (для дальнейшего получения медиа контента данного профиля)

**Comment by Tehzombie-secret** [comment]
Добавил опцию просмотра отзывов без фото на товаре. Это решает проблему?

**Comment by Nextan** [comment]
Ну это во все небыло проблемой, но благодарю за ответ и содействие в данном вопросе!
Хорошего Вам дня!
