### ISSUE TITLE
Сайт лёг?

### ISSUE THREAD

**Issue by Want2BeRocker** [Tehzombie-secret/Marketplace-previewer#31]
Не открывает карточки товаров и новые отзывы тоже не подгружаются (их попросту нет). Всё началось где то 6-10 февраля.

**Comment by Tehzombie-secret** [comment]
Разбираюсь, спасибо

**Comment by Tehzombie-secret** [comment]
Снова работает

**Comment by Tehzombie-secret** [comment]
А сейчас? Выглядит как какая-то плавающая ошибка, пока не могу поймать полноценно

**Comment by Tehzombie-secret** [comment]
Пока еще смотрю, выглядит как проблема площадки, но пока не уверен что с этим делать

**Comment by Tehzombie-secret** [comment]
Как будто бы пока не воспроизводится. Закрою ишью
