### ISSUE TITLE
Отставание отзывов от wb

### ISSUE THREAD

**Issue by keymiks** [Tehzombie-secret/Marketplace-previewer#32]
Добрый день. Отзывы на сайте собраны до 6 февраля, если переходить на wb, то они отличаются (на wb больше новых).

**Comment by Tehzombie-secret** [comment]
Добрый день, есть пример?

**Comment by Tehzombie-secret** [comment]
Поправил

**Comment by keymiks** [comment]
Очень оперативно, спасибо!
