### ISSUE TITLE
Есть ли в планах другие маркетплейсы?

### ISSUE THREAD

**Issue by Want2BeRocker** [Tehzombie-secret/Marketplace-previewer#33]
Хотелось бы узнать о планах (если они есть). Джум и озон ждать стоит? Джум тоже очень популярен и полон отзывов

**Comment by VagrantAI-c** [comment]
Изначально я закладывал в архитектуру такую возможность расширения, но пока заниматься этим времени абсолютно нет

**Comment by Tehzombie-secret** [comment]
Изначально я закладывал в архитектуру такую возможность расширения, но пока заниматься этим времени абсолютно нет
