### ISSUE TITLE
Not possible to run the full solution (api + front)

### ISSUE THREAD

**Issue by gravityperson** [Tehzombie-secret/Marketplace-previewer#4]
Hi, just tried to run the solution.
So faced a couple of issues:
1. after running "npm start" starts only frontend
2. after running api (several commands) it doesn't start

Expected result:
there's a readme.md file filed with all the needed information how to run the solution.

PS-могу помочь, дискорд здесь gravityperson#1679

**Comment by Tehzombie-secret** [comment]
it should be `npm run dev:ssr`. Readme updated

помочь с чем?

**Comment by gravityperson** [comment]
> it should be `npm run dev:ssr`. Readme updated
> 
> помочь с чем?

с развитием angular части
