### ISSUE TITLE
Частично перестали загружаться последние фото

### ISSUE THREAD

**Issue by keymiks** [Tehzombie-secret/Marketplace-previewer#40]
Частично перестали загружаться последние фото, от продукту к продукту ситуация разная

<img width="1055" alt="image" src="https://github.com/Tehzombie-secret/Marketplace-previewer/assets/161119439/cfa250e1-1b00-4556-a55b-eefd48256b01">

**Comment by Tehzombie-secret** [comment]
Поправил
