### ISSUE TITLE
Геопозиция 

### ISSUE THREAD

**Issue by Delonn4** [Tehzombie-secret/Marketplace-previewer#41]
Есть ли возможность смотреть геопозицию фото или отзыва ? Можно было бы вынести в отдельный раздел, но не знаю сохраняет ли вб эти данные и может ли передавать. Либо есть ли возможность отслеживать сам пункт выдачи напрямую ? Был сайт downloader se, который недавно закрылся и мог находить геопозицию пользователя который выкладывал фото в vsco, но там понятно что это обусловлено геопозицией самого фото, которое человек загрузил, есть ли возможность сделать также?

**Comment by Tehzombie-secret** [comment]
Все метаданные режутся при заливке на маркетплейс, невозможно выявить такое
