### ISSUE TITLE
Профили не открываются/не загружаются.

### ISSUE THREAD

**Issue by Nextan** [Tehzombie-secret/Marketplace-previewer#42]
Здравствуйте!
Заметил такой момент;
Открыв любой фото-отзыв, профиль который её добавил, вообще не загружается, идёт бесконечная загрузка(кружок) и всё.
![изображение](https://github.com/user-attachments/assets/45c6c8fb-1273-4799-8952-e8d72176d978)

При попытке перехода по имени, открывает в новом окне просто пустое окно, где чисто шапка: Профиль и всё.
![изображение](https://github.com/user-attachments/assets/93061f80-1b30-4a71-92ce-8a15bd1df4ef)

_p.s. Добавил бы скриншоты под "спойлер", но тут увы его видимо нету :)_

**Comment by Tehzombie-secret** [comment]
Да, база уже совсем не справляется из-за объема данных, добавлю ресурсов сколько не жалко, но по-хорошему надо переделывать кардинально

**Comment by Nextan** [comment]
Ну если Вам доставляет неудобства данный "проект", почему бы его не закрыть?
Смотря конечно какие у Вас планы, желания и.т.п факторы, дело то конечно Ваше, моя задача была лишь сообщить о найденой ошибке/проблеме ;)

**Comment by Tehzombie-secret** [comment]
из-за количества отзывов, сам запрос на получение всех отзывов конкретного пользователя висит сильно, там 40 гигов отзывов. Фиксится шардированием, но мне надо это изучать. Скорее всего еще ударит по ценнику

**Comment by Tehzombie-secret** [comment]
у меня не слишком времени чтобы заниматься этим, к сожалению, даже с донатами

**Comment by triplenick** [comment]
Может дашь инструкции именно как бд поднять? Я клонировал репо чисто ради интереса, но подключиться к бд не смог из-за отсутствия логина и пароля, как я понял. Но тут вопрос скорее в том, как на своем энде поднять бд и фетчить отзывы.

**Comment by Tehzombie-secret** [comment]
бд - монга, она у меня хостится в облаке, для локальной разработки можно поднять локально

Поднятие базы:
1. В файле [src/server/services/mongodb/mongodb.service.ts в строчке 253](https://github.com/Tehzombie-secret/Marketplace-previewer/blob/main/src/server/services/mongodb/mongodb.service.ts#L253) поменять хост на свой
2. Прокинуть креды, тут два варианта:
2.1 Создать в руте папку `.mongodb`, там ожидается два файла - root.crt с сертификатом для монги и credentials.json, где в формате `{ "user": "...", "password": "..." }` ожидается логопасс
2.2 Прокинуть через энвы переменные MONGODB_USER, MONGODB_PASSWORD, MONGODB_CERT с соответствующим наполнением из пункта выше

Запустить скрапинг контента в базу можно раскомментив эту строчку https://github.com/Tehzombie-secret/Marketplace-previewer/blob/main/src/server/server.ts#L81
Запуск - `npm run build:ssr` и затем `npm run serve:ssr`

**Comment by Tehzombie-secret** [comment]
Сейчас отзывы занимают 40 гигов места, есть ощущение что монга тут и не должна справляться

**Comment by Tehzombie-secret** [comment]
Нашел время поковыряться часок, вроде поправил, не знаю что там будет по задержкам - если будет отлетать где-то или работать медленно - создавайте новые ишью
