### ISSUE TITLE
Не прогружает сведения

### ISSUE THREAD

**Issue by andrey12345678901** [Tehzombie-secret/Marketplace-previewer#44]
![Screenshot_2024-08-25-05-16-05-877_com android chrome](https://github.com/user-attachments/assets/f1ce59be-77c8-4175-8d94-f620d44a06fc)

**Comment by Tehzombie-secret** [comment]
Такой категории не существует, надо проваливаться сразу внутрь. Сайт не отображает пока что такой функционал
