### ISSUE TITLE
Как в отзывах найти ID пользователя

### ISSUE THREAD

**Issue by MaxJackHuman** [Tehzombie-secret/Marketplace-previewer#45]
Пересмотрел код страницы и фото, не пойму как на самом маркете найти ID пользователя, чтобы потом использовать его в Marketplace-previewer

**Comment by Tehzombie-secret** [comment]
никак, вся функциональность профиля с маркетплейса выпилена. Заходи на сам товар и ищи там нужный отзыв и переходи в профиль
