### ISSUE TITLE
Не показывает все отзывы 

### ISSUE THREAD

**Issue by iris2231** [Tehzombie-secret/Marketplace-previewer#5]
Не показывает все отзывы о товарах 
![image](https://user-images.githubusercontent.com/128947149/227751965-e8100445-e9f7-4b79-a784-1b40d2d4f03d.png)
![image](https://user-images.githubusercontent.com/128947149/227751986-53671ba0-e4ee-46c3-8c7a-8f46ff4a81ec.png)

**Comment by Tehzombie-secret** [comment]
сколько из этих отзывов - с фотографиями? Я сразу фильтрую по этому принципу. Есть еще второе ограничение - платформа отдает 500 последних отзывов, даже если их фактически больше

**Comment by iris2231** [comment]
Сравните 
Здесь отзывов  с фото 430  https://www.wildberries.ru/catalog/29419530/detail.aspx?targetUrl=AB 
Здесь всего с  фото 105 https://mkpl-fdbck-view.ru/wb/product/29419530

**Comment by iris2231** [comment]
Вы можете починить? Просто по другому никак не открыть в новой вкладке профиля сайта. wildberries. ru не позовляет открывать, а id профиля нигде не найти. Ваш сайт лучший по просмотру отзывов.

**Comment by Tehzombie-secret** [comment]
я посмотрю, могу пока предварительно подтвердить что платформа поменяла способ выдачи отзывов

**Comment by Tehzombie-secret** [comment]
поправил

**Comment by Tehzombie-secret** [comment]
фикс распространяется на все товары. Если будут какие-то несоответствия, то оформляйте новый ишью

заглядываю иногда
