### ISSUE TITLE
Не открываются профили

### ISSUE THREAD

**Issue by kulstas** [Tehzombie-secret/Marketplace-previewer#50]
Контент на страницах профилей по типу: https://mkpl-fdbck-view.ru/wb/person/@ не подгружаются.

В консоле выдается ошибка: un {headers: mt, status: 504, statusText: 'Gateway Timeout', url: '/api/1/user/73631105?global=true', ok: false, …}

**Comment by Lokiodinson73** [comment]
Долго уже так лежит(

**Comment by Tehzombie-secret** [comment]
да, это известная проблема, может когда-нибудь смогу починить 

https://github.com/Tehzombie-secret/Marketplace-previewer/issues/42
